discord:
    discord_client_id: "YOUR_CLIENT_ID_HERE"
    discord_client_secret: "YOUR_CLIENT_SECRET_HERE"
    discord_redirect_uri: "YOUR_REDIRECT_URI_HERE"
    discord_bot_token: "YOUR_BOT_TOKEN_HERE"

webserver:
    host: 0.0.0.0
    debug: true
    port: 30789

administration:
    maintenance_message: "<h1>Your maintenance_message goes here</h1><p>It even supports basic HTML!</p>"
    maintenance_mode: true
    readonly: false
    web_admins:
        - "YOUR_DISCORD_USER_ID_HERE"

database:
    host: "localhost"
    port: 3306
    user: "YOUR_DB_USER_HERE"
    password: "YOUR_DB_PASSWORD_HERE"
    database: "YOUR_DB_NAME_HERE"