discord_client_id: "YOUR_CLIENT_ID_HERE"
discord_client_secret: "YOUR_CLIENT_SECRET_HERE"
discord_redirect_uri: "YOUR_REDIRECT_URI_HERE"

host: 0.0.0.0
debug: true
port: 30789

maintenance_message: "<h1>Your maintenance_message goes here</h1><p>It even supports basic HTML!</p>"
maintenance_mode: true
readonly: false
web_admins:
    - "YOUR_DISCORD_USER_ID_HERE"
